import React from "react";
import "./index.css";

const Cookies = () => {
  return (
    <div className="cookies-container">
      <div className="cookies-content">
        <h1 className="cookies-title"><span className="gameover">GameOver</span> Cookie Policy</h1>
        <br />
        <h2 className="cookies-title">Definitions and key terms</h2>
        <p className="cookies-text">
          To help explain things as clearly as possible in this Cookie Policy,
          every time any of these terms are referenced, are strictly defined as:{" "}
          <br /> <br />
          Cookie: small amount of data generated by a website and saved by your
          web browser. It is used to identify your browser, provide analytics,
          remember information about you such as your language preference or
          login information. <br /> Company: when this policy mentions
          “Company,” “we,” “us,” or “our,” it refers to STREAMS CHARTS, a UA
          Public Organization registered in Ukraine, 01104, Kyiv city, Princes
          of Ostrog street 46/2, 28 that is responsible for your information
          under this Cookie Policy. <br /> Device: any internet connected device
          such as a phone, tablet, computer or any other device that can be used
          to visit Esports Charts and use the services. <br /> Personal Data:
          any information that directly, indirectly, or in connection with other
          information — including a personal identification number — allows for
          the identification or identifiability of a natural person. <br />{" "}
          Service: refers to the service provided by Esports Charts as described
          in the relative terms (if available) and on this platform. <br />{" "}
          Third-party service: refers to advertisers, contest sponsors,
          promotional and marketing partners, and others who provide our content
          or whose products or services we think may interest you. <br />{" "}
          Website: Esports Charts’s site, which can be accessed via this URL:
          https://escharts.com/. <br />
          You: a person or entity that is registered with Esports Charts to use
          the Services.
        </p>

        <h2 className="cookies-title">Introduction</h2>
        <p className="cookies-text">
          This Cookie Policy explains how Esports Charts and its affiliates
          (collectively "Esports Charts", "we", "us", and "ours"), use cookies
          and similar technologies to recognize you when you visit our platform,
          including without limitation and any related URLs, mobile or localized
          versions and related domains / sub-domains ("Websites"). It explains
          what these technologies are and why we use them, as well as the
          choices for how to control them.
        </p>
        <h2 className="cookies-title">What is a cookie?</h2>
        <p className="cookies-text">
          A cookie is a small text file that is stored on your computer or other
          internet connected device in order to identify your browser, provide
          analytics, remember information about you such as your language
          preference or login information. They're completely safe and can't be
          used to run programs or deliver viruses to your device.
        </p>
        <h2 className="cookies-title">
          What type of cookies does Streams Charts use?
        </h2>
        <p className="cookies-text">
          Cookies can either be session cookies or persistent cookies. A session
          cookie expires automatically when you close your browser. A persistent
          cookie will remain until it expires or you delete your cookies.
          Expiration dates are set in the cookies themselves; some may expire
          after a few minutes while others may expire after multiple years.
          Cookies placed by the website you're visiting are called “first party
          cookies” <br /> <br />. Strictly Necessary cookies are necessary for
          our platform to function and cannot be switched off in our systems.
          They are essential in order to enable you to navigate around the
          platform and use its features. If you remove or disable these cookies,
          we cannot guarantee that you will be able to use our platform. <br />{" "}
          <br /> We use the following types of cookies in our platform:
        </p>
        <h2 className="cookies-title">Essential Cookies</h2>
        <p className="cookies-text">
          We use essential cookies to make our platform work. These cookies are
          strictly necessary to enable core functionality such as security,
          network management, your cookie preferences and accessibility. Without
          them you wouldn't be able to use basic services. You may disable these
          by changing your browser settings, but this may affect how the
          Websites function.
        </p>
        <h2 className="cookies-title">Performance and Functionality Cookies</h2>
        <p className="cookies-text">
          These cookies are used to enhance the performance and functionality of
          our platform but are non-essential to their use. However, without
          these cookies, certain functionality like videos may become
          unavailable or you would be required to enter your login details every
          time you visit the platform as we would not be able to remember that
          you had logged in previously. <br /> <br />
          We use cookies served by Cloudflare to help detecting malicious
          visitors and minimising a blocking of legitimate users. Cloudflare
          also helps serving static assets, eg. the code snippets that are
          responsible for the website’s design. Further information on how
          Cloudflare collects and uses this data can be found at:
          https://www.cloudflare.com/privacypolicy/.
        </p>
        <h2 className="cookies-title">Changes To Our Cookie Policy</h2>
        <p className="cookies-text">
          We may change our Service and policies, and we may need to make
          changes to this Cookie Policy so that they accurately reflect our
          Service and policies. Unless otherwise required by law, we will notify
          you (for example, through our Service) when we make changes to this
          Cookie Policy and give you an opportunity to review them before they
          go into effect. Then, if you continue to use the Service, you will be
          bound by the updated Cookie Policy. If you do not want to agree to
          this or any updated Cookie Policy, you can delete your account by
          request on privacy@escharts.com.
        </p>
      </div>
    </div>
  );
};

export default Cookies;
